const express = require('express')
const auth = require('../../middleware/auth')
const router = express.Router()
const {Register,Login,Loaduser, Follow, Postdata,Likes,Unlikes, Getfollowers, Getfollowing, Getuser, Getpost,Comment,Getmypost, Updatepic, Myfollowpost,Unfollow, Reset, GetPostByUser, allUsers} = require('../controller/controller')

router.post('/register',Register)
router.post('/login',Login)
router.get('/load',auth,Loaduser)
router.put('/follow',auth,Follow)
router.put('/unfollow',auth,Unfollow)
router.post('/postdata',auth,Postdata)
router.post('/reset',Reset)
router.get('/allusers',allUsers)
router.get('/allposts',Getpost)
router.get('/userposts/:id',GetPostByUser)
router.get('/myposts',auth,Getmypost)
router.put('/like',auth,Likes)
router.put('/unlike',auth,Unlikes)
router.get('/followers',Getfollowers)
router.get('/following',Getfollowing)
router.get('/getuser/:id',Getuser)
router.put('/comment',auth,Comment)
router.get('/followposts',auth,Myfollowpost)
router.patch('/updatedp',auth,Updatepic)

module.exports = router